### ISSUE TITLE
pgbouncer - adding user does not work

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator-examples#100]
I'm trying to add another user to the pgbouncer config.  However, when I edit the secret <cluster>-pgbouncer it immediately overwrites my changes to pgbouncer-users.txt key.  How am I supposed to either update the pgbouncer password or add another user to access pgbouncer?

**Comment by digitalcraig** [comment]
You add users to the cluster spec, see https://access.crunchydata.com/documentation/postgres-operator/5.0.4/tutorial/user-management/

**Comment by alrooney** [comment]
I tried that and that does not work.  A user is created and the secret for that user suggests that it can connect to pgbouncer.  But the pgbouncer secret with pgbouncer-users.txt does not get updated and the user is not added to the pgbouncer service.  When I check the pgbouncer log I see this:
```
2022-03-24 03:08:50.348 UTC [8] WARNING C-0x564dc4f34470: hippo/(nouser)@10.1.129.39:38088 pooler error: no such user
```

**Comment by digitalcraig** [comment]
I opened a similar issue on the operator repo. Was this adding a user after the cluster was created or adding any users at all? 

https://github.com/CrunchyData/postgres-operator/issues/3095

**Comment by alrooney** [comment]
This was adding a user after the cluster was created.  But was worried that might be an issue so I deleted the pgbouncer proxy in the postgrescluster definition which deleted pgbouncer.  And then I re-added it so it created pgbouncer again.  It did recreate the secret for pgbouncer but still did not add the additional user.  Hope that helps.

**Comment by digitalcraig** [comment]
Ok, sounds like you experienced a similar issue to mine. Please take at look at the issue I linked and see if anything there helps. Maybe you can provide the logs that I could not.

**Comment by alrooney** [comment]
@digitalcraig I figured out my issue and maybe have a clue as to why it worked for you sometimes but not other times.  It does not work if the user you are trying to access through pgbouncer is a superuser.  The auth function that gets installed specifically declines superusers.   So to workaround this you can either remove superuser privileges from the user you are trying to use with pgbouncer or you can edit the auth function in the db to remove the line where it declines superusers.

**Comment by digitalcraig** [comment]
@alrooney Ah, I see. In my case, I wasn't trying to add a superuser. I was adding a new database and a user with permissions to that database only. What made it work was to delete the postgrescluster object and create it again with the new user rather than edit it to add the new user.

**Comment by benjaminjb** [comment]
Feel free to reopen this if this is still an issue, or better, reopen the issue on the postgres-operator repo, but I'm going to close it since it seems resolved.
