### ISSUE TITLE
CRD does not have all options?

### ISSUE THREAD

**Issue by mhaddon** [CrunchyData/postgres-operator-examples#115]
The Helm and Kustomize CRD:
https://github.com/CrunchyData/postgres-operator-examples/blob/main/kustomize/install/bases/crd/bases/postgres-operator.crunchydata.com_postgresclusters.yaml

Is missing:
https://github.com/CrunchyData/postgres-operator/blob/master/docs/content/references/crd.md#postgresclusterspecusersindexpassword

And possibly other options too?

**Comment by benjaminjb** [comment]
Yes, as part of the workflow, the CRD in the `main` branch of the `postgres-operator-examples` repo will lag behind the CRD in (1) the `devel` branch of this repo and (2) the `postgres-operator` repo.

For instance, currently (10/13/22), the `devel` branch here matches what is in the `postgres-operator` repo, but does not match the `main` branch here. This is part of the expected workflow: our current release should match `main`, but our development work should match `devel`.
