### ISSUE TITLE
Kustomize install has too large CRD objects

### ISSUE THREAD

**Issue by zerkms** [CrunchyData/postgres-operator-examples#131]
On upgrade from 5.0.x to 5.1.0 when you apply kustomized manifests it fails to update CRDs:

```
"The CustomResourceDefinition \"postgresclusters.postgres-operator.crunchydata.com\" is invalid: metadata.annotations: Too long: must have at most 262144 bytes"
```

Which is not suprising - it's ~615KB now.

**Comment by benjaminjb** [comment]
Hello, we have run into this problem before as well. Have you tried applying the manifest with the flag `--server-side`? This information is present in our [docs](https://access.crunchydata.com/documentation/postgres-operator/5.1.1/quickstart/#installation) but not in this repo.

Please try with that flag, and if this is still a problem, please reopen this issue so we can solve it.

**Comment by zerkms** [comment]
I don't use `kubectl` with `kustomize` directly - I first generate yaml manifests with kustomize on one machine (effectively here they are just templates filled with data), then on the other - `kubectl` takes those static complete yaml manifests and applies them.

Thanks for `--server-side` flag, I have never heard of it and I will check if `kubectl apply` with it changes anything.

**Comment by zerkms** [comment]
UPD: yep, `--server-side` totally helped, thanks!
