### ISSUE TITLE
PGUpgrade data checksum disable

### ISSUE THREAD

**Issue by zposloncec** [CrunchyData/postgres-operator-examples#134]
Postgres operator: 5.1.1

old cluster does not use data checksum, but PGUpgrade has data checksum on by default. Is there a way to disable checksum?

**Comment by jmckulk** [comment]
Hello @zposloncec, the PGUpgrade does not have a way to disable checksum. How did you create the old cluster? Are you running into any errors? Can you share the logs from the upgrade job?

**Comment by zposloncec** [comment]
Hey @jmckulk. our cluster was replicated from the standalone docker which had checksum disabled. I've ended up doing scaled down with disk preserved and enabling checksum on each instance using `pg_checksums --enable`. It's best practice to have data checksum enabled so it was worth to enable it that way. Thank you.
