### ISSUE TITLE
some questions about postgres operator upgrade

### ISSUE THREAD

**Issue by olivejing** [CrunchyData/postgres-operator-examples#137]
Hi expert,

I installed crunchy postgres operator and postgrescluster V5.0.5, now, i wanted to upgrade them. 
From postgres-operator-examples code, it uses postgres-operator-upgrade image and creates upgrade deployment. This upgrade deployment is used to upgrade postgrescluster? and how to build postgres-operator-upgrade image?  I did not find  postgres-operator-upgrade image in Makefile.

**Comment by danielzhanghl** [comment]
refer to https://github.com/CrunchyData/postgres-operator/issues/3218

**Comment by shinyaaa** [comment]
I am also having the same problem.
I want to build postgres-operator-upgrade, but I can't find the Dockerfile for it.

**Comment by benjaminjb** [comment]
Thanks @danielzhanghl for jumping in, and I'll just reiterate and expand for @olivejing 

1) the postgres-operator-upgrade is for upgrading postgres clusters (not the operator) and is a new feature available in 5.1.x. See this blog post: https://www.crunchydata.com/blog/easy-major-postgresql-upgrades-using-pgo-v51

2) For upgrading the operator itself, see https://access.crunchydata.com/documentation/postgres-operator/v5/upgrade/kustomize/

Hope that helps!
