### ISSUE TITLE
postgres-repo-host pod in CrashLoopBackOff - "environment: /dev/fd/62: Text file busy"

### ISSUE THREAD

**Issue by getkedar1981** [CrunchyData/postgres-operator-examples#144]
We have a 3 node kubernetes cluster and deployed these examples in a namespace. ( PGO was deployed in namespace and not clusterwide ) 

This was deployed using steps shared under : https://access.crunchydata.com/documentation/postgres-operator/5.0.0/quickstart/ 

- We have tried cluster wide operator and namespace based too ( using kustomize ) . In both cases this issue was seen.

Steps : After installation ,restart only "postgres-repo-host-0" pod and its enters CrashLoopBackOff state. 

Observed that the postgres-repo-host-0 pod goes into CrashLoopBackOff with container 'pgbackrest-config' shows logs as "environment: /dev/fd/62: Text file busy"

#kubectl logs postgres-repo-host-0 pgbackrest-config -n postgres-operator
environment: /dev/fd/62: Text file busy

The pod postgres-repo-host-0 had to be restarted a few times to come back to running state.

This was observed on k8s v1.19 and PGO v 5.0.0, 5.1.0 and also latest ones.

Its seems the monitor function - pgbackrest-config container -  is generating this error at step - exec {fd}<> <(:)

Can you please suggest any solution for this issue?

**Comment by getkedar1981** [comment]
Can anyone please take a look at this and suggest?

**Comment by getkedar1981** [comment]
Can anyone please suggest if I can add delay/sleep in or before the monitor function for the pod postgres-repo-host-0 and container pgbackrest-config as the PGO cleans it up after pod restart.

**Comment by benjaminjb** [comment]
Since you opened up a duplicate issue on the postgres-operator repo (where I think this issue probably belongs), I'm going to close this one and comment over there.
