### ISSUE TITLE
Kubernetes Node Selector

### ISSUE THREAD

**Issue by adhityan26** [CrunchyData/postgres-operator-examples#145]
Postgres Operator: v5.1.2

Is there any way to determine node-selector on the PostgresCluster definition?
I'm using GKE for my kubernetes cluser, and I have multiple node pool on the kubernetes cluster, I want to install Database Cluster only on specific node pool, is there any way to achieve this?

Thanks in advance

**Comment by tjmoore4** [comment]
Hello @adhityan26, please take a look at the relevant [High Availability documentation](https://access.crunchydata.com/documentation/postgres-operator/5.1.2/tutorial/high-availability/), particularly the `Node Affinity` section. I believe these features should provide what you need to achieve your desired outcome.
