### ISSUE TITLE
pgAdmin4 - 'psycopg2.extensions.Column' object has no attribute '_asdict'

### ISSUE THREAD

**Issue by DarkAngelStrike** [CrunchyData/postgres-operator-examples#162]
While using the syntax given in the documentation to deploy pgAdmin4 (https://access.crunchydata.com/documentation/postgres-operator/5.2.0/architecture/pgadmin4) : 

```userInterface:
    pgAdmin:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:ubi8-4.30-4
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
```

I get the following error message `'psycopg2.extensions.Column' object has no attribute '_asdict'` when trying to expand hippo :

![image](https://user-images.githubusercontent.com/716555/198143223-8aafddb5-c193-4280-ab7d-d4a31ece6ee6.png)

![image](https://user-images.githubusercontent.com/716555/198146142-5adcb8cf-19b8-4205-a255-f1e5f9665aa1.png)

**Comment by cbandy** [comment]
@DarkAngelStrike This has been addressed with crunchydata/crunchy-containers#1480 and is planned for inclusion in the next release. Until then, you can downgrade to tag `ubi8-4.30-2` to avoid this issue.
