### ISSUE TITLE
Latest image pull fails crunchy-postgres-ha:centos8-13.4-0

### ISSUE THREAD

**Issue by farcasmihai91** [CrunchyData/postgres-operator-examples#17]
Latest image pull fails crunchy-postgres-ha:centos8-13.4-0
Error:

> Failed to pull image "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.4-0": rpc error: code = Unknown desc = Error response from daemon: unknown: This container version is no longer available from the Crunchy Data Developer Program. For information on accessing these containers, please contact info@crunchydata.com.

**Comment by jkatz** [comment]
This is resolved. Thanks for reporting!
