### ISSUE TITLE
new images for PGO are not available 

### ISSUE THREAD

**Issue by kelt1k** [CrunchyData/postgres-operator-examples#186]
Error response from daemon: manifest for registry.developers.crunchydata.com/crunchydata/postgres-operator:ubi8-5.3.1-0 not found: manifest unknown: manifest unknown

**Comment by mkjpryor** [comment]
This change seems to have been merged to `main` before the images have been pushed...

**Comment by ValClarkson** [comment]
Hi @kelt1k 

Sorry for the confusion the release pr for v5.3.1 was pushed accidentally, it has been reverted and will be pushed again as soon as the images are available.
