### ISSUE TITLE
Postgres_13 image listed in values.yaml returns error

### ISSUE THREAD

**Issue by Andrew920** [CrunchyData/postgres-operator-examples#190]
When attempting to pull `postgres_13` image listed here:
https://github.com/CrunchyData/postgres-operator-examples/blob/7242d033f602e464fadaf256e1664b1c9da0cac7/helm/install/values.yaml#L22

This error is returned:
```
Failed to pull image "registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-13.10-0": rpc error: code = Unknown desc = Error response from daemon: unknown: This container version is no longer available from the Crunchy Data Developer Program. For information on accessing these containers, please contact info@crunchydata.com.
```

**Comment by benjaminjb** [comment]
I'm closing this here since the conversation is happening elsewhere; and we have PRs in flight to remove the images from this repo that are no longer applicable. Sorry for the trouble here!
