### ISSUE TITLE
Example dashbords don't work with self-managed grafana (9.4.7)

### ISSUE THREAD

**Issue by jcpunk** [CrunchyData/postgres-operator-examples#199]
I attempted to import the dashboards from kustomize/monitoring/dashboards into my grafana and it appears the datasource is hard coded as I receive the error:

```
Failed to upgrade legacy queries Datasource PROMETHEUS was not found
```

**Comment by tony-landreth** [comment]
Hi @jcpunk! These dashboards expect a [datasource](https://grafana.com/docs/grafana/latest/datasources/) that we've configured [here](https://github.com/CrunchyData/postgres-operator-examples/blob/main/kustomize/monitoring/grafana-datasources.yaml). Our docs for using the monitoring stack can be found [here](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/monitoring/). I hope that clears things up.
