### ISSUE TITLE
Example for LB service

### ISSUE THREAD

**Issue by ZuSe** [CrunchyData/postgres-operator-examples#21]
Hi,

I saw in the operator project that support for providing pgbouncer or ha as LoadBalancer service has been added.
Just wanted to ask if there is already any kind of docs for it that explain how to apply it?
We would be very interested in that functionality.

Best
Patrick

**Comment by jkatz** [comment]
Selection of a service type is not yet released. Any documentation around it will be in a future release.

In the interim, if you need a LoadBalancer Service, you will need to create one on your own and point it at the objects you are looking to serve.
