### ISSUE TITLE
postgres-startup init container is broken

### ISSUE THREAD

**Issue by synchris** [CrunchyData/postgres-operator-examples#22]
Postgres startup container is broken.

install: cannot change permissions of ‘/pgdata/pg13’: No such file or directory

I know this goes to postgres-operator

After applying the sample cluster the node failed to start caused by postgres-startup initContainer.

**Comment by jkatz** [comment]
If there is a bug, please open this in the [PGO](https://github.com/CrunchyData/postgres-operator) project. You will need to provide a lot more detail as this gives almost no guidance on where to start looking.
