### ISSUE TITLE
Create tags in this repo

### ISSUE THREAD

**Issue by PaulVerhoeven1** [CrunchyData/postgres-operator-examples#226]
In my opinion it would be nice if this repo gets a tag when a new version of the operator is released.

Now 5.4 is released of the operator there should be a tag / release called 5.4, then if you want to install an older version of the operator you know which CRD's, image versions and value files were provided in that release. Now if you want to install an older version based on these examples you need go back to specific commit.

**Comment by tjmoore4** [comment]
Hi @PaulVerhoeven1

Thank you for reaching out. The examples repo is designed to allow users to easily take PGO out for a test drive, as explained in our [quickstart](https://access.crunchydata.com/documentation/postgres-operator/v5/quickstart/). As such, we expect users to update these examples or create their own manifests as needed. To read more about release tags, please see our [FAQ](https://access.crunchydata.com/documentation/postgres-operator/latest/faq#where-are-the-release-tags-for-pgo-v5). Hope this helps!
