### ISSUE TITLE
Publish Helm chart

### ISSUE THREAD

**Issue by sathieu** [CrunchyData/postgres-operator-examples#23]
Please publish the Helm chart.

It can be done with [chart-releaser](https://github.com/helm/chart-releaser-action) or [helm-publish](https://github.com/marketplace/actions/helm-publish) Github action, for example.

**Comment by jkatz** [comment]
I'm not opposed and overall the PR looks good. I think we need to understand how this fits into our release process and documentation.

**Comment by sathieu** [comment]
@jkatz Usually, Helm charts have independent release cycle. An alternative would be use a `staging` directory, like Gatekeeper does, but this is a [complex](https://github.com/open-policy-agent/gatekeeper/tree/master/cmd/build/helmify) [machinery](https://github.com/open-policy-agent/gatekeeper/tree/master/manifest_staging).

**Comment by politician** [comment]
This would solve this issue https://github.com/CrunchyData/postgres-operator/issues/2231

@jkatz A released chart is important to:

1. Truly use the operator in a IaC/GitOps way and simplify upgrade management (for example using bots to open PR's and test upgrades automatically when a new version is released)
2. Simplify consumption for newcomers:
    ```sh
    helm repo add crunchydata https://crunchydata.github.io/helm-charts
    helm install postgres-operator crunchydata/postgres-operator
    ``` 

@sathieu  However, I'd recommend doing it in another repo, it's weird to have charts released from a repo called `postgres-operator-examples`. Ideally that'd be from the official repo [postgres-operator](https://github.com/CrunchyData/postgres-operator) but there is already a GH pages site published from it. @jkatz I would recommend creating a [helm-charts](https://github.com/CrunchyData/helm-charts) repo.

**Comment by torbendury** [comment]
Hello everyone! The chart itself looks very good and is well-documented, what burps us from using it in production is the fact that we need to check out the GitHub repo instead of being able to manage the life cycle from a Helm repository. Is this feature on your roadmap somehow?

**Comment by mymasse** [comment]
Until the chart is published in a Helm repository could this repository at least be tagged when the chart is updated that way we wouldn't have to clone the main branch.

**Comment by ath88** [comment]
This is breaking for our usage of the crunchydata operator. Please publish a helm chart.

**Comment by bstrdsmkr** [comment]
Just adding to the list of engineers spending way too much time trying to manage the helm chart. This makes for a terrible user experience and the bar to fix it is pretty low.

**Comment by karloramone** [comment]
Is there any plan on publishing the chart in the future?

**Comment by benjaminjb** [comment]
We have released the Helm chart as noted here: https://github.com/CrunchyData/postgres-operator-examples/pull/28#issuecomment-1361970898

(I won't bother copy-pasting Andrew's whole answer, but he covers everything I would want to say about it. Please reopen this issue if there's something else about this topic that isn't addressed.)
