### ISSUE TITLE
Add example for pgo.yaml config

### ISSUE THREAD

**Issue by uberspot** [CrunchyData/postgres-operator-examples#24]
Could you also add an example in the helm chart for a pgo deployment that also modifies the config perhaps? 

https://access.crunchydata.com/documentation/postgres-operator/4.5.0/configuration/configuration/

So it's clearer how it can be modified

**Comment by jkatz** [comment]
This repo is solely for examples for v5 of PGO. For requests on PGO itself and its documentation, please refer to the [Postgres Operator](https://github.com/CrunchyData/postgres-operator) project.

**Comment by uberspot** [comment]
You can ignore the 4.5.0 version of my request. Please consider this issue being for v.5 or whatever the latest is.
The issue is the same either way. How do you configure options like "disableFSGroup" once the example under helm/ is deployed?
