### ISSUE TITLE
Typo in postgres-exporter image tag?

### ISSUE THREAD

**Issue by lepicodon** [CrunchyData/postgres-operator-examples#241]
Hello,

It seems there's a typo in the Helm Chart values, specifically in the postgres-exporter image tag:
https://github.com/CrunchyData/postgres-operator-examples/blob/main/helm/install/values.yaml#L34

It currently is: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:**ubi8-0.15.0-0**
I believe it should be: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:**ubi8-5.5.0-0**

Thank you for checking!

**Comment by andrewlecuyer** [comment]
Hi @lepicodon!

The image tag you are seeing is indeed correct, and is related to the following change in the [Crunchy Postgres for Kubernetes v5.5.0 release](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/5.5.x#550):

> Transitioning the crunchy-postgres-exporter image into a component container, thereby decoupling it from the postgres-operator.

More specifically, with this change the exporter container is now tagged according to the software version (i.e., the Postgres Exporter version), as described under the [Container Tags](https://access.crunchydata.com/documentation/postgres-operator/latest/references/components#container-tags) section of the docs.

And finally, I can confirm the image you referenced can indeed be pulled:

```bash
$ podman pull registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-0.15.0-0
Trying to pull registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-0.15.0-0...
Getting image source signatures
Copying blob 8cc261754eea skipped: already exists
Copying blob efe07ddbecec skipped: already exists
Copying blob 2417ebac4d69 skipped: already exists
Copying config 1bed8475ee done
Writing manifest to image destination
1bed8475ee27fb3eff29b92573c2937b4219396d81cec32019c1c66071754d3a
```
