### ISSUE TITLE
podSecurity doesn't include seccomPorfile

### ISSUE THREAD

**Issue by camaeel** [CrunchyData/postgres-operator-examples#248]
In order to fulfill restricted PodSecurity policy requirements, helm chart should add as a default on the pod or container level:

```
seccompProfile:
  type: "RuntimeDefault"
```

**Comment by andrewlecuyer** [comment]
Hi @camaeel, thanks for the feedback.  I agree this would be a great addition to the Crunchy Postgres for Kubernetes (CPK) installers.

I can also confirm that we have a story in the CPK backlog to look at this change.  Additionally, PR's are always welcome!

And finally, I will note that any update will also need to consider how this setting is handled by OpenShift Security Context Constrains (SCC's).

Thanks again!

**Comment by benjaminjb** [comment]
Hi @camaeel,

As of our latest release (v5.6.0), SeccompProfile is now set to RuntimeDefault in all Pods .  Please see the following documentation for more information:
* https://access.crunchydata.com/documentation/postgres-operator/latest/releases/5.6.x
* https://access.crunchydata.com/documentation/postgres-operator/latest/references/crd/5.6.x/postgrescluster#postgresclusterspecinstancesindexcontainersindexsecuritycontextseccompprofile

I'm going to close this issue now, but if you have any issues or questions feel free to re-open this issue or reach out to us on our [Discord server](https://discord.com/invite/a7vWKG8Ec9).
