### ISSUE TITLE
`postgres_14` image is not available

### ISSUE THREAD

**Issue by budimanjojo** [CrunchyData/postgres-operator-examples#255]
The `registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.11-0` is not available in the registry although being the default value of `postgres_14`.

**Comment by neoighodaro** [comment]
This entirely broke our prod kubernetes cluster.

**Comment by bap-dev** [comment]
same here!

**Comment by neoighodaro** [comment]
<img width="482" alt="Screenshot 2024-02-26 at 10 07 40" src="https://github.com/CrunchyData/postgres-operator-examples/assets/807318/004d820e-e7bc-4430-9454-313b9fc4f49b">

it would seem it was removed.

**Comment by bap-dev** [comment]
btw. the whole registry seems to not be availible anymore:
https://github.com/CrunchyData/postgres-operator/issues/3859

**Comment by budimanjojo** [comment]
They shouldn't bump the `postgres_14` in the `values.yaml` file if they're not gonna update the image anymore. Such a weird decision. They should either just keep the value the same or just remove the entire `postgres_14` and notify the users.

**Comment by neoighodaro** [comment]
> They shouldn't bump the `postgres_14` in the `values.yaml` file if they're not gonna update the image anymore. Such a weird decision. They should either just keep the value the same or just remove the entire `postgres_14` and notify the users.

Do you know a quick fix? I am trying to avoid even upgrading at this point as its too quick a response, but since prod is down, this may be the only option.

**Comment by budimanjojo** [comment]
@neoighodaro you can just put something like this in your `values.yaml` file:
```
relatedImages:
  postgres_14:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.10-0
```

**Comment by bap-dev** [comment]
same thing: curl -L https://registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.10-0
{ "errors":[{"code":"404","message":"This container version is no longer available from the Crunchy Data Developer Program. For information on accessing these containers, please contact info@crunchydata.com." }]

**Comment by bap-dev** [comment]
yeah, I can confirm this. 14.10-0 is working 14.11-0 not!

**Comment by bap-dev** [comment]
Still asking myself about the reason why an older version is availible but not a newer one... and how long will the old one stay alive...

**Comment by neoighodaro** [comment]
probably not long but at least i can buy some time to test an upgrade to 15...

**Comment by bap-dev** [comment]
> probably not long but at least i can buy some time to test an upgrade to 15...

good point!

**Comment by budimanjojo** [comment]
@andrewlecuyer Thanks for the response!

I think the question from me is why is this line here:
https://github.com/CrunchyData/postgres-operator-examples/blob/9cbce08338f412d410f9bc238ce22d0fbcaef26d/helm/install/values.yaml#L20

Got updated from this PR: https://github.com/CrunchyData/postgres-operator-examples/pull/254

Can the default value be reverted back to `registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.10-0` so it doesn't defaulted to a non-existance image?

**Comment by andrewlecuyer** [comment]
@budimanjojo sorry about the confusion!

The image tag you referenced actually shouldn't have been included, and has since been reverted/removed.

This means Crunchy Postgres for Kubernetes will no longer attempt to rollout a non-existent image tag after upgrading, and any existing clusters will simply remain running with their current image tags (giving you a chance to upgrade Postgres, etc. as described above).  Or you can always customize the install with [additional related images](https://access.crunchydata.com/documentation/postgres-operator/latest/guides/configuring-cluster-images#configuring-installers) as well.
