### ISSUE TITLE
Example for setting work_mem needed

### ISSUE THREAD

**Issue by DE110283** [CrunchyData/postgres-operator-examples#261]
I'm deploying PG database using PostgresCluster (PGO) in gitops mode - meaning deploying PostgresCluster yaml to Openshift. I like to increase the work_mem, but I can't find a sample / explanation how to set work_mem using PostgresCluster yaml.
Please provide / advise - many thanks in advance!

**Comment by useafterfree** [comment]
I think this will help you: https://access.crunchydata.com/documentation/postgres-operator/5.4/tutorials/day-two/customize-cluster#customize-tls

**Comment by benjaminjb** [comment]
Thanks, @useafterfree, that's just what I would point to. I'm going to close this issue now, but @DE110283, feel free to reopen this issue if this documentation doesn't help.
