### ISSUE TITLE
Postgres Operator crashes

### ISSUE THREAD

**Issue by chrkspr** [CrunchyData/postgres-operator-examples#270]
Postgres Operator crashes when installed with helm.

Used commit: ae452671c32e87d8baf0d6dfdb7fc079c546693f

values.yaml:
```
singleNamespace: true
```

Error logs from pgo:
```
k -n  mynamespace logs -l postgres-operator.crunchydata.com/control-plane=pgo
...
W0610 15:19:38.052551       1 reflector.go:324] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1beta1.CrunchyBridgeCluster: crunchybridgeclusters.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:mynamespace:pgo" cannot list resource "crunchybridgeclusters" in API group "postgres-operator.crunchydata.com" in the namespace "mynamespace"
...
```
"runchybridgeclusters" is missing in kubernetes role pgo (https://github.com/CrunchyData/postgres-operator-examples/blob/main/helm/install/templates/role.yaml).

**Comment by benjaminjb** [comment]
Hey @chrkspr, thanks, we're looking into this now

**Comment by dsessler7** [comment]
This issue has been resolved. Please pull the latest commits in main to fix your issue.

**Comment by jaitaiwan** [comment]
Has the main chart been updated? I can only see 5.6.0 still in the chart repo?

**Comment by dsessler7** [comment]
Yes, the main chart was updated. The 5.6.0 version is the Crunchy Postgres for Kubernetes version, so that will only get bumped when we release a new version of CPK.

**Comment by jaitaiwan** [comment]
@dsessler7 What I think this means is that for automated GitOps systems like flux is that the OCI Repo won't trigger a reconciliation unless the chart version has been updated.

**Comment by marvin-w** [comment]
> @dsessler7 What I think this means is that for automated GitOps systems like flux is that the OCI Repo won't trigger a reconciliation unless the chart version has been updated.

I have exactly this issue, any hint on how to resolve?

**Comment by jaitaiwan** [comment]
Seems like the best bet might be to open a new issue referencing this one. I made a PR to allow for custom env vars, that could at least be used to upgrade the chart without an uninstall. It’s not a good solution though.
