### ISSUE TITLE
Fix helm image.repository to include image name

### ISSUE THREAD

**Issue by ron1** [CrunchyData/postgres-operator-examples#36]
Fix helm image.repository to include image name to be consistent with relatedImages.*.repository which already includes image name. This change also allows the postgres-operator image name to be overridden which is a secondary benefit.

**Comment by ron1** [comment]
@jkatz This issue has nothing to do with the "related images" format. Instead, it focuses exclusively on the "postgres-operator" image format.

Currently, this chart hard-codes the image name to be "postgres-operator". I want the ability to change its image name to say "mirrored-postgres-operator" following the pattern Rancher uses when they bundle a third-party image with their product. An example of this Rancher approach is available here: https://github.com/rancher/rancher/releases/download/v2.5.11/rancher-images.txt.

Please consider re-opening this issue and applying the changes I proposed above.

Thanks.

**Comment by jkatz** [comment]
@ron1 Got it. That should be fairly easy to tackle.

**Comment by ron1** [comment]
@jkatz Perfect! Thanks much!
