### ISSUE TITLE
cannot change permissions of pgdata/pg13 no such file postgres-startup nss-wrapper-init

### ISSUE THREAD

**Issue by xtpclark** [CrunchyData/postgres-operator-examples#43]
Hello,

Deployed the operator with Rancher UI, added the postgres-operator-examples repo main and installed pgo and postgrescluster charts.  In Rancher, in the cluster under Pods:

  hippo-pgbouncer-686ff789f6-jwrxr - OK 
  hippo-repo-host-0  - OK
  pgo-dd4776866-gl9pf - OK
   
However... hippo-instance1-nzpg-0  has an error:  Containers with incomplete status: [postgres-startup nss-wrapper-init] 
and the log is:  
Initializing ...
::postgres-operator: uid::26
::postgres-operator: gid::26
::postgres-operator: postgres path::/usr/pgsql-13/bin/postgres
::postgres-operator: postgres version::postgres (PostgreSQL) 13.4
::postgres-operator: config directory::/pgdata/pg13
::postgres-operator: data directory::/pgdata/pg13
install: cannot change permissions of ‘/pgdata/pg13’: No such file or directory

registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.4-1

Thanks

**Comment by jkatz** [comment]
This is for reporting issues/feature requests specifically with the `postgres-operator-examples`. If you need support with PGO usage, please see [support](https://access.crunchydata.com/documentation/postgres-operator/v5/support/)

**Comment by xtpclark** [comment]
Sorry, I thought I was in the proper place because the postgres-operator-examples repo has the helm charts.

**Comment by jkatz** [comment]
No worries.
