### ISSUE TITLE
Postgresql Custom image

### ISSUE THREAD

**Issue by DTvGe45vc** [CrunchyData/postgres-operator-examples#50]
Hello
I want to use custom postgresql image. For instance "supabase/postgres"
For it I rebuild image and prepared postgres user id (26) by dockerfile like your image "registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.4-1".

Also after start image I get the error: "Error: container has runAsNonRoot and image has non-numeric user (postgres), cannot verify user is non-root"

What I need to do for starting?

**Comment by DTvGe45vc** [comment]
My Dockerfile


```
From supabase/postgres:13.3.0
ARG UNAME=postgres
ARG UID=26
ARG GID=26
RUN groupmod -g 3000 $(getent group | grep $GID |cut -d':' -f1 )
RUN groupmod -g $GID $UNAME
RUN usermod -u $UID -g $GID $UNAME
USER $UNAME
```

**Comment by jkatz** [comment]
This repo is specifically for working with the examples around [PGO](github.com/CrunchyData/postgres-operator). For support issues, please see the [support](https://access.crunchydata.com/documentation/postgres-operator/v5/support/) section in the documentation.
