### ISSUE TITLE
Missing option to override Image Registry

### ISSUE THREAD

**Issue by alex1989hu** [CrunchyData/postgres-operator-examples#52]
If you want to use a proxy like a pull through cache it is easier to override the registry itself and leave the repository name as it is.

As of now, we need to override the whole repository to let us able to use custom registry which is fragile due to the fact that repository name can be changed.

On the other hand, I see this convention can be found in the huge Bitnami Helm Chart collection

**Comment by jkatz** [comment]
Image conventions seem to still be an open item in upstream Helm:

https://github.com/helm/helm/issues/7754

I've read through this a few times. I agree with the rationale of your proposal, but need to think on this a little bit.

**Comment by benjaminjb** [comment]
To revisit this topic: splitting the image into registry, repository, and tag makes some sense to me; but it also doesn't seem to be the conventional way to indicate images, and I worry that the change may be confusing.

At this point, I'm leaning towards closing this out; if you need this change, well, this is the examples repo -- they're meant to be changed and iterated on, and you clearly can do that. Does it disrupt your use of this chart if this change is not there?

**Comment by alex1989hu** [comment]
Dear @benjaminjb, it does not disrupt. The PR is almost one year and I am happy to use it in a private fork. I just wanted to avoid having a fork to let me able to override the registry (e.g. using a pull through cache) without knowing the repository and the image tag.

Feel free to close this issue.

**Comment by benjaminjb** [comment]
Sure thing!
