### ISSUE TITLE
Missing Helm value to disable debug logging

### ISSUE THREAD

**Issue by alex1989hu** [CrunchyData/postgres-operator-examples#58]
As of now there is no option to disable the debug logging level within the Helm Chart, it default to `true`.

I would be happy if we can disable it by an option in the Helm Chart values file.

https://github.com/CrunchyData/postgres-operator-examples/blob/e0d6196b90248cebbcff6f6ac4f7ddbc1db44aa7/helm/install/templates/manager.yaml#L22-L23

The environment variable value is being read by the Operator here:

https://github.com/CrunchyData/postgres-operator/blob/7bb5d719dc5035a4bda2d8261503dadea83d77d7/cmd/postgres-operator/main.go#L44-L51

What do you think about it? What option shall enable/disable debug logging?

**Comment by jkatz** [comment]
@alex1989hu Yup, we should have an option to disable debug level logs.
