### ISSUE TITLE
Allow Helm CRD management to be disabled

### ISSUE THREAD

**Issue by ron1** [CrunchyData/postgres-operator-examples#59]
It is common for mainstream CRD-based workloads to allow Helm CRD management to be externalized from the main chart. One approach used by Rancher, the Elastic Cloud on Kubernetes Operator, and others externalizes crds into their own chart, for example, charts eck-operator and eck-operator-crds.

Another lighter-weight approach adopted by jetstack/cert-manager and kyverno/kyverno to name a few leverages an "installCRDs" boolean property to allow Helm CRD management to be disabled. This approach at least provides the option to disable CRD management.

The current approach used by this chart that relies on the "/crds" directory to install crds but not update them is problematic, especially for gitops scenarios. Consider adopting one of the other strategies described above.

**Comment by sathieu** [comment]
I only know a few charts handling this correctly:

- gatekeeper
  - [crds directory](https://github.com/open-policy-agent/gatekeeper/tree/3ba8e93049b542a0c273e60a57ca03bd24d95dd7/charts/gatekeeper/crds)
  - upgrade with a ["hook"](https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/templates/upgrade-crds-hook.yaml) (ClusterRole+ClusterRoleBinding+ServiceAccount+Job)
 - velero:
   - [crds directory](https://github.com/vmware-tanzu/helm-charts/tree/58e695b586b80a7cec593955ba49f503bba77406/charts/velero/crds)
   - [upgrade-crds Job](https://github.com/vmware-tanzu/helm-charts/blob/58e695b586b80a7cec593955ba49f503bba77406/charts/velero/templates/upgrade-crds.yaml)
   - [cleanup-crds Job](https://github.com/vmware-tanzu/helm-charts/blob/58e695b586b80a7cec593955ba49f503bba77406/charts/velero/templates/cleanup-crds.yaml)

Other methods are partial, and the eck-operator way requires [extra manual steps](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-upgrading-eck.html#k8s-beta-to-ga-upgrade).

**Comment by benjaminjb** [comment]
I've entered this into the backlog, but would welcome if anyone wants to open a PR for that.
