### ISSUE TITLE
How to pass args to initdb?

### ISSUE THREAD

**Issue by bobbyd0g** [CrunchyData/postgres-operator-examples#66]
[Edit: My apologies, I realize now this belongs on the main postgres-operator issues board and have posted it there instead]

Hello, I need a database with initdb args `--lc-collate=C` and `--lc-ctype=C` for Matrix Synapse, and it's not entirely clear how to do so from the docs. Nothing I see in the CRD reference looks right -- `PostgresCluster.spec.patroni` only appears to cover dynamic config -- and I searched many forum & issue posts. Is there a way to get these arguments to initdb with a v5 PostgresCluster?

**Comment by benjaminjb** [comment]
https://github.com/CrunchyData/postgres-operator/issues/2924
