### ISSUE TITLE
Role label collides with metrics

### ISSUE THREAD

**Issue by zerkms** [CrunchyData/postgres-operator-examples#7]
`postgres-operator.crunchydata.com/role` label is rewritten to just `role`:

https://github.com/CrunchyData/postgres-operator-examples/blob/73941b92277650947b9c8b02f3f72ed3901d77ea/kustomize/monitoring/prometheus-config.yaml#L46-L48

then it collides with some metrics, eg:

```
# HELP ccp_pg_stat_statements_total_calls_count Total number of queries run per user/database
# TYPE ccp_pg_stat_statements_total_calls_count gauge
ccp_pg_stat_statements_total_calls_count{dbname="hippo-ha",role="_crunchypgbouncer",server="localhost:5432"} 10
ccp_pg_stat_statements_total_calls_count{dbname="hippo-ha",role="hippo-ha",server="localhost:5432"} 45
ccp_pg_stat_statements_total_calls_count{dbname="hippo-ha",role="postgres",server="localhost:5432"} 2
```

It would end up rewriting role from the metric to the role from labels.

**Comment by benjaminjb** [comment]
I can't replicate this problem, and it looks like prometheus has a scrape config setting (`honor_labels`) for when labels would conflict; i.e., when I check that metric, the label we relabel here comes through as `role` but the original role label gets automatically relabeled as `exported_role`.

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config

Closing this now, but please reopen if this is still a problem you're seeing. (The files here are meant to be examples for users to alter as necessary, but of course we want them to be in a good state too, so thanks for bringing this up.)
