### ISSUE TITLE
Duplicate service value should actually be dataSource

### ISSUE THREAD

**Issue by johnf-staybull** [CrunchyData/postgres-operator-examples#72]
Line https://github.com/CrunchyData/postgres-operator-examples/blob/24f5849ebb8931a6ccabb6341a4a7d81355a911f/helm/postgres/templates/postgres.yaml#L148 should actually be:
```
dataSource:
```
I updated it in my downloaded template file and it worked when changing it to `dataSource`. If you look at the template file it is pretty obvious that this is a typo.

**Comment by benjaminjb** [comment]
Thanks, this was fixed in https://github.com/CrunchyData/postgres-operator-examples/pull/95
