### ISSUE TITLE
unable to configure the monitoring for Crunchy

### ISSUE THREAD

**Issue by hariyedlapalli** [CrunchyData/postgres-operator-examples#73]
Please report any bugs or feature requests specific to the PGO Examples that are in this repository. This includes anything around the examples for Kustomize and Helm.

For any bugs or feature request related to PGO itself, please visit https://github.com/CrunchyData/postgres-operator

postgres-operator-examples-main]$ ~/kubectl apply -f kustomize/monitoring/crunchy_grafana_dashboards.yml --validate=false
error: unable to decode "kustomize/monitoring/crunchy_grafana_dashboards.yml": Object 'Kind' is missing in '{"apiVersion":1,"providers":[{"disableDeletion":false,"folder":"","name":"crunchy_dashboards","options":{"path":"$GF_PATHS_PROVISIONING/dashboards"},"orgId":1,"type":"file","updateIntervalSeconds":3}]}'

**Comment by jkatz** [comment]
Opened twice, responding in https://github.com/CrunchyData/postgres-operator/issues/2959
