### ISSUE TITLE
How to find a list of available docker images for pgbouncer/posgres and so on?

### ISSUE THREAD

**Issue by EugenMayer** [CrunchyData/postgres-operator-examples#74]
I found https://hub.docker.com/r/crunchydata/crunchy-postgres but this does only offer 13.5 images.

Since i will need to update the images from time to time, how to finde the newest available images for 

 - registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-12*
 - registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer
 
Also it sounds wrong to use `registry.developers.crunchydata.com` for production use - are those the actual production images?

I found docs like https://access.crunchydata.com/documentation/postgres-operator/5.0.4/tutorial/update-cluster/ but still no hint on the actual image index for the available tags?

Thanks!

**Comment by james-callahan** [comment]
FWIW I've been finding out by looking at https://access.crunchydata.com/containerinfo/containerversions.txt

**Comment by EugenMayer** [comment]
Looks like the best way to do that is https://www.crunchydata.com/developers/download-postgres/container

**Comment by benjaminjb** [comment]
Some notes on this:
(a) that Docker hub is no longer part of the process for releasing new images;
(b) that `containerversions.txt` isn't accurate about what's available in `registry.developers.crunchydata.com`, but about what's available to customers, for whom we maintain more images than are publicly available.
(c) and yes, @EugenMayer, those images aren't meant for production per se, and for production, we steer people towards our support team/customer access.
