### ISSUE TITLE
Postgres chart is not installable by default

### ISSUE THREAD

**Issue by Dan0x54** [CrunchyData/postgres-operator-examples#75]
When installing the postgres chart with no added values, it fails:
```bash
helm install example postgres
Error: INSTALLATION FAILED: template: postgrescluster/templates/postgres.yaml:193:14: executing "postgrescluster/templates/postgres.yaml" at <eq .Values.openshift false>: error calling eq
: incompatible types for comparison
```
Manually setting with `--set openshift=false` fixes it and it installs fine. However it should probably just work without it. Uncommenting the openshift value in helm/postgres/values.yaml should fix it

My Helm version:
```bash
helm version
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

**Comment by andrewlecuyer** [comment]
@Dan0x54 this appears to be an issue with Helm `v3.7.x`.  Therefore, please upgrade to the latest version of Helm (Helm `v3.8.0`).  While I am able to reproduce the error you are seeing with Helm `v3.7.1` and Helm `v3.7.2`, I can confirm that the install works as expected with Helm `v3.8.0`:

```bash
$ helm version
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}
$ helm install pgo helm/postgres
NAME: pgo
LAST DEPLOYED: Mon Jan 24 20:39:31 2022
NAMESPACE: postgres-operator
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for deploying a Crunchy PostgreSQL cluster!
...
```

Please note that it is important that we are able to distinguish between an unset `openshift` environment variable (which means OpenShift auto-detection should be attempted PGO) vs. a user explicitly setting `openshift ` to either `true` or `false` (which means auto-detection should be disabled, and PGO should simply use the value provided by the user).

**Comment by Dan0x54** [comment]
@andrewlecuyer Thanks, that makes sense though it would be worth putting that version incompatibility somewhere in the docs / README or better yet, shifting around the logic so it reads:
```yaml
{{- if .Values.openshift }}
  {{- if eq .Values.openshift true }}
  openshift: true
  {{- else }}
  openshift: false
  {{- end }}
```
Then the "eq" function is only evaluated if .Values.openshift is explicitly defined.

**Comment by Dan0x54** [comment]
@andrewlecuyer Thanks for explaining that - it makes sense that having it unset would imply an auto detection. It appears helm 3.8 was only released 16 hours before I'm writing this comment so I imagine a lot of people would encounter this issue. Might be worth shifting round the logic so that it works for both versions:
```yaml
{{- if haskey .Values "openshift" }}
  {{- if .Values.openshift }}
    openshift: true
  {{- else }}
    openshift: false
  {{- end }}
{{- end }}
```
