### ISSUE TITLE
pgbackrest + s3 minio Name or service not known

### ISSUE THREAD

**Issue by osaffer** [CrunchyData/postgres-operator-examples#82]
Version: 5.0.4-0

Hi,

When I try to use a private minio the format of the address is incorrect.

I have the following configuration: 

backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
      configuration:
      - secret:
          name: pgo-s3-creds
      global:
        repo1-path: /pgbackrest/postgres-operator/dbname/repo1
        repo1-retention-full: "14"
        repo1-retention-full-type: time
      repos:
      - name: repo1
        s3:
          endpoint: "minio.example.com"
          bucket: "postgres"
          region: "whatever"
        schedules:
          full: "0 10 * * *"
          incremental: "0 * * * *"

But in the log of PGO : 
level=error msg="unable to create stanza" error="command terminated with exit code 49: ERROR: [049]: unable to get address for 'postgres.minio.example.com': [-2] Name or service not known\n" file="internal/controller/postgrescluster/pgbackrest.go:2320" func="postgrescluster.(*Reconciler).reconcileStanzaCreate" name=dbname namespace=postgres-operator reconciler=pgBackRest reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.0.4-0

For what reason the format is not correct ?

Thank you very much

**Comment by dimitrigraf** [comment]
Hi!

I had a similar error once when using our own S3 backend. Make sure that the endpoint is really correct. See the following closed issue for more details:  https://github.com/CrunchyData/postgres-operator/issues/2836

Hope this helps!

Chers.

**Comment by osaffer** [comment]
Hi @dimitrigraf ,

Thanks for your reply.

For information for the test, I dont cypher the communication.

So I try minio.example.com the format is not correct

If I try to specify protocol http://minio.example.com, same error than the issue you specified
I tried minio.example.com:80, again the format is not correct.

Am I obliged to use https ?

Regards

**Comment by dimitrigraf** [comment]
I'm not sure about mandatory https. Maybe someone else can answer that. I guess it depends on the storage backend and how the endpoint is configured. I would just try if I were you.

**Comment by osaffer** [comment]
it is just default configuration of minio, nothing special
For example I have kasten installed, it can backup on the minio without any problem. I use the same endpoint.

I guess there is a bug with a s3 compatible as minio.

I dont think I try to do an exotic configuration :D

**Comment by osaffer** [comment]
Hi 

I found that : 
The following URI styles are supported:
host - Connect to bucket.endpoint host.
path - Connect to endpoint host and prepend bucket to URIs.
default: host
example: repo1-s3-uri-style=path

**Comment by osaffer** [comment]
So now I have : 
time="2022-01-31T14:15:39Z" level=error msg="unable to create stanza" error="command terminated with exit code 101: ERROR: [101]: TLS error [1:336130315] wrong version number\n" file="internal/controller/postgrescluster/pgbackrest.go:2320" func="postgrescluster.(*Reconciler).reconcileStanzaCreate" name=contrefacon namespace=postgres-operator reconciler=pgBackRest reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.0.4-0

in the global section:
global:
        repo1-path: /pgbackrest/postgres-operator/dbname/repo1
        repo1-s3-uri-style: path
        repo1-retention-full: "14"
        repo1-retention-full-type: time
        repo1-storage-verify-tls: "n"
        repo1-storage-port: "9000"

**Comment by osaffer** [comment]
Finally I configured TLS for minio, and now It works perfectly.

Nevertheless. the parameter repo1-s3-uri-style: path is important
Otherwise the format will be bucket.hostname

And as the it is seflsigned certifacte : 

repo1-storage-verify-tls: "n"

**Comment by im-lh** [comment]
> 

I have the same error as you, Could you please tell me how configured TLS for minio in kubernetes

**Comment by osaffer** [comment]
Hi,

This is my configuration :  

image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
      configuration:
      - secret:
          name: pgo-s3-creds
      global:
        repo1-path: /pgbackrest/postgres-operator/contrefacon/repo1
        repo1-s3-uri-style: path
        repo1-retention-full: "14"
        repo1-retention-full-type: time
        repo1-storage-verify-tls: "n"
        repo1-storage-port: "9000"

The minio is not deployed on the kubernetes, but it is a docker on separated VM
How to enable TLS on minio : 
cat openssl.conf 
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
C = RU
ST = RU
L = Moscow
O = yuyu
OU = yoyo
CN = minio.example

[v3_req]
subjectAltName = @alt_names

[alt_names]
IP.1 = X.X.X.X
DNS.1 = minio.example

Generate your certificate : 
openssl req -new -x509 -nodes -days 730 -keyout private.key -out public.crt -config openssl.conf

Then start the docker : 
docker run -d --name miniotls -p 9000:9000 -v /opt/data:/data -v /opt/ssl:/root/.minio/certs minio/minio server /data

**Comment by benjaminjb** [comment]
Nice community support!
