### ISSUE TITLE
ccp_replication_status_byte_lag does not exist anymore

### ISSUE THREAD

**Issue by zerkms** [CrunchyData/postgres-operator-examples#9]
I think only `ccp_replication_lag_replay_time` is available now

**Comment by zerkms** [comment]
`ccp_replication_slots_active` does not exist either

**Comment by zerkms** [comment]
And `ccp_backrest_last_runtime_backup_runtime_seconds` is renamed to `ccp_backrest_last_info_backup_runtime_seconds` now

**Comment by benjaminjb** [comment]
We've recently updated which version of pgMonitor we are inheriting from, which are in line with most of your comments here:

1) `ccp_replication_status_byte_lag` and `ccp_backrest_last_runtime_backup_runtime_seconds` have been replaced
2) but I still see `ccp_replication_slots_active`

If this is an error, please bring it up in the pgMonitor repo where this material is inherited.
