### ISSUE TITLE
Can this be tagged?

### ISSUE THREAD

**Issue by budimanjojo** [CrunchyData/postgres-operator-examples#90]
I'm planning to use this postgres-operator in my [FluxCD](https://fluxcd.io/) managed kubernetes cluster but there's no way to do it without tagging. I'm using [renovatebot](https://github.com/renovatebot/renovate) to track new releases and then Flux will deploy the changes into the cluster automatically. I have read the `Where are the release tags for PGO v5?` FAQ, but this repository is meant to be the entrypoint of us to install PGO, isn't it?

**Comment by ValClarkson** [comment]
Hi @budimanjojo 

This repo is an examples repo to allow users to easily take our operator out for a test drive.  as explained [here](https://access.crunchydata.com/documentation/postgres-operator/v5/quickstart/) in our quickstart.  We expect users to update these or create their own manifests.

Information about release tags are located in our docs [here](https://access.crunchydata.com/documentation/postgres-operator/5.0.5/faq/)
