### ISSUE TITLE
Connect to application in default namespace

### ISSUE THREAD

**Issue by RampedIndent** [CrunchyData/postgres-operator-examples#93]
I followed the documentation to create a postgress "hippo" cluster which is in the "postgress-operator" namespace, is there a way to connect the users made in the postgress Cluster file to applications in the "default" namespace? Since the generated pguser secrets are only in the postgress-operator namespace. I have looked through the documentation provided at https://access.crunchydata.com/documentation/postgres-operator/5.0.5/ and have been unable to find much about namespaces.

**Comment by RampedIndent** [comment]
I'm using the kustomise method btw

**Comment by jshimko** [comment]
@RampedIndent Kubernetes secrets can only be accessed from the namespace they live in.  For cases like yours, you could either deploy the cluster in the namespace you need it in or just grab the value you need from that secret and manually set it for the service that needs it (via env var, etc).

```sh
kubectl get secret -n $NS $PGO_SECRET -o jsonpath='{.data.pgbouncer-uri}' | base64 -d

# outputs:  postgresql://user:pw@host:5432/dbname
```

**Comment by RampedIndent** [comment]
Solution found: install [reflector](https://github.com/emberstack/kubernetes-reflector) this allows for secrets to be automatically mirrored between namespaces
the required annotations can be added with a yaml file, just make sure the name of the secret is the same as the auto generated secret. 
```apiVersion: v1
kind: Secret
metadata: 
  name: hippo-pguser-inventree
  namespace: postgres-operator
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
```

**Comment by mloskot** [comment]
I've just upgraded to latest PGO 5.3 and as far as I can tell, no secrets reflection is necessary

I simply created `PostgresCluster` manifest based on [kustomize/postgres/postgres.yaml](https://github.com/CrunchyData/postgres-operator-examples/blob/f94c261ef1c83bca9aa3e5d9894710ab3e03cd7e/kustomize/postgres/postgres.yaml) changing name and adding namespace:

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres-example
  namespace: customer-example
```

and it worked:

```
$ kubectl get -n my-example pods | grep postgres
postgres-example-backup-whxv-rct7p   0/1     Completed   0          18m
postgres-example-instance1-6lt2-0    4/4     Running     0          19m
postgres-example-repo-host-0         2/2     Running     0          19m
```

```
$ kubectl get -n my-example secrets | grep postgres
postgres-example-cluster-cert                          Opaque   3      16m
postgres-example-instance1-6lt2-certs                  Opaque   6      16m
postgres-example-pgbackrest                            Opaque   5      16m
postgres-example-pguser-example-pgo                    Opaque   8      16m
postgres-example-replication-cert                      Opaque   3      16m
```

and I was able to connect to the database too.
